from config.settings import settings
print("PROJECT_NAME")
print(settings.project_name)
print("ENVIRONMENT")
print(settings.environment)
print("KAFKA_BOOTSTRAP_SERVERS")
print(settings.kafka_bootstrap_servers)
print("POSTGRES_HOST")
print(settings.postgres_host)
print("POSTGRES_PORT")
print(settings.postgres_port)
print("POSTGRES_DATABASE")
print(settings.postgres_database)
print("POSTGRES_USER")
print(settings.postgres_user)
print("POSTGRES_URL")
print(settings.postgres_url)
